.TH daisync 1
.SH NAME
daisync \- rsync-based time-machine-backup
.SH SYNOPSIS
.B daisync
[\fB-h]
[\fB-v]
[...]
.SH DESCRIPTION
.B daisync
is a rsync-based tool developed by Manhong Dai in MBNI, U of Michigan to daily backup petabyte storages. 

.SH OPTIONS
.TP
.BR \-h
for detail
.TP
.BR \-v
version and copyright
