#!/usr/bin/env bash
set -eu
set -o pipefail
trap "exit 1" TERM
function helpme {
	if [ $# -gt 0 ]
	then
		echo -e "$1" 1>&2
	else
		grep '#' /proc/$$/fd/255 | sed -n '/^#HELPME_START/,/^#HELPME_END/p' | grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2 #20220313
	fi
	PGID=$(cut -d ' ' -f 5 /proc/$$/stat)
	kill -s TERM -- -$PGID
}
function hash_command {
	hash $1 &> /dev/null || helpme "ERR-008: missing command $1"
}
ARCHIVE=""
CLONESTYLE=hardlink
KEEP=""
NUM=10
REMOVE=""
UPDATEDB=NO
ARGLIST=$@
OPT_SHORT="hvn:c:a:s:r:k:d"
OPT_LONG="help,version,num-of-backups:clone-style:,archive:,source:,removal-percentage:,keep:,updatedb"
OPTS=$(getopt -o $OPT_SHORT --long $OPT_LONG -n daisync -- "$@")
eval set -- "$OPTS"
while [ $# -gt 0 ]
do
	case "$1" in
#HELPME_START
#NAME
#	daisync, a modifiable-time-machine backup tool
#EXAMPLE
#	mkdir -p backup1/0000; daisync -c reflink -s someone@localhost:dir1/ backup1
#	mkdir -p backup2/0000; daisync -s someone@localhost:"dir1\ dir2" backup2
#SYNOPSIS
#	daisync [OPTION]... DEST
#DESCRIPTION
		-h | --help) #print help information
			helpme ;;
		--version) #print version information
			helpme "20220402" ;;
		-v )	#verbose output
			set -x
			shift ;;
		-n | --num-of-backups)	#NUM, maximum number of transient backups, default 10
			let NUM=$2 || helpme "ERR-001: invalid number for -n: $2"
			shift 2 ;;
		-c | --clone-style)	#hardlink/reflink/none. Default is 'hardlink', unchanged files are hard-linked across all backups. With 'reflink', 'cp --reflink' are used prior to 'rsync', which doesn't support reflink yet as of 20020326. With 'none', unchanged files are not cloned and are only in 0000
			CLONESTYLE=$2
			[ "$CLONESTYLE" = "hardlink" -o "$CLONESTYLE" = "reflink" -o "$CLONESTYLE" = "none" ] || helpme "ERR-016: invalid parameter for -c: $2"
			shift 2 ;;
		-a | --archive)	#weekly/monthly/yearly, interval of permanent backups
			[ "$2" = "weekly" -o "$2" = "monthly" -o "$2" = "yearly" ] || helpme "ERR-002: invalid paramter: -a $2"
			ARCHIVE=$2
			shift 2 ;;
		-s | --source)	#SOURCE, such as "SERVER1:/home", "-e 'ssh -p 22' SERVER1:/home", "--exclude=*-excluded-from-daisync SERVER:/home". SOURCE is directly passed to rsync, can be local, rsync:// or rsync over remote shell, including ssh and rsh. Multiple '-s' are supported to backup some setup such as gluster storage nodes
			SOURCES+=("$2")
			shift 2 ;;
		-r | --removal-percentage)	#PERCENTAGE, see '-k' below
			let REMOVE=$2 || helpme "ERR-005: invalid number for -r: $2"
			shift 2 ;;
		-k | --keep) #KEEP, keep removing the oldest transient backup until the DEST storage usage is below PERCENTAGE or there are only KEEP of backups left
			let KEEP=$2 || helpme "ERR-006: invalid number for -k: $2"
			shift 2 ;;
		-d | --updatedb)	#generate locate database to find file very quickly. A sample command of finding file is 'locate -d DEST/0000/.daisync-locate.db myfile'
			hash_command updatedb
			UPDATEDB=YES
			shift 1 ;;
		--)
			shift
			break ;;
		*)
			break ;;
#AUTHOR
#	Manhong Dai, MNI, U of Michigan
#COPYRIGHT
#	Copyright © 2002-2022 University of Michigan. License GPLv3+: GNU
#	GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
#	This is free software: you are free to change and redistribute it.
#	There is NO WARRANTY, to the extent permitted by law.
#HELPME_END
	esac
done

for CMD in flock rsync fuser df
do
	hash_command $CMD
done
set +u
[ ${#SOURCES[@]} -gt 0 ] || helpme "ERR-007: missing -s"
set -u
[ $# -eq 1 ] || helpme "ERR-009: missing DEST"
DEST=$1
[ -d "$DEST" ] || helpme "ERR-010: no such a directory '$DEST'"
[ -d "$DEST/0000" ] || helpme "ERR-011: run 'mkdir -p $DEST/0000' to explicitly initialize \"$DEST\" as a daisync directory"
[ -z "$REMOVE" -a -z "$KEEP" ] || [ -n "$REMOVE" -a -n "$KEEP" ] || helpme "ERR-013: -k and -r need be used together"
[ ${#SOURCES[@]} -eq 1 -o "$CLONESTYLE" = "hardlink" ] || helpme "ERR-014: multiple -s can work with '-c hardlink' only"
(
	if ! flock -n 77
	then
		fuser "$DEST/.daisync-lock"
		helpme "ERR-015: a daisync is still running, process id is above"
	fi
	echo "[$(date '+%F %H:%M:%S')]#daisync begin (daisync $ARGLIST)"
	if [ $NUM -gt 1 ]
	then
		((LAST=NUM-1))
		LAST=$(printf "%04d" $LAST)
	fi
	if [ ! -d "$DEST/.daisync" ]
	then
		if [ "$CLONESTYLE" = "none" ]
		then
			mv "$DEST/0000" "$DEST/.daisync"
			mkdir "$DEST/0000"
			mv "$DEST/.daisync/.daisync-*" "$DEST/0000/" 2> /dev/null || :
		elif [ "$CLONESTYLE" = "hardlink" ]
		then
			mkdir "$DEST/.daisync"
		elif [ "$CLONESTYLE" = "reflink" ]
		then
			touch -a "$DEST/0000/.daisync-log"
			mkdir -p "$DEST/.daisync-reflink"
			if ! cp -a --reflink=always "$DEST/0000/.daisync-log" "$DEST/.daisync-reflink"
			then
				rm -r "$DEST/.daisync-reflink"
				helpme "ERR-017: \"$DEST\" doesn't support reflink. Try the latest version of xfs, btrfs, cifs, nfs 4.2, etc."
			fi
			cp -au --reflink=always "$DEST/0000/." "$DEST/.daisync-reflink"
			mv "$DEST/.daisync-reflink" "$DEST/.daisync"
		else
			helpme "ERR-019"
		fi
	fi
	rm -f "$DEST/.daisync/.daisync-df"
	if [ "$REMOVE" != "" ]
	then
		for ((SLEEP=1; ;SLEEP++))
		do
			ps $$ &> /dev/null || break
			((CUR_DFPCT=$(df -P "$DEST" | tail -n 1 |awk '{print $5}' | sed -e "s/%//") ))
			if [ $CUR_DFPCT -ge $REMOVE ]
			then
				(( CUR_BKNUM=$( (cd $DEST && ls -d ???? .daisync 2>/dev/null ) | wc -l ) ))
				[[ $CUR_BKNUM -le $KEEP ]] && break
				LAST=$( (cd $DEST && ls -d ???? | grep -v 0000) | sort -r | head -n 1 )
				if [ -n "$LAST" ]
				then
					echo "[$(date '+%F %H:%M:%S')]#daisync removing $LAST"
					rm -rf "$DEST/$LAST"
					continue
				fi
			elif [ ! -d "$DEST/.daisync" ]
			then
				break
			fi
			if [ $SLEEP -gt 60 ]
			then
				sleep 60
			else
				sleep $SLEEP
			fi
		done
	fi &
	mapfile -t SOURCES < <(shuf -e -- "${SOURCES[@]}")
	for SRC in "${SOURCES[@]}"
	do
		if [ "$CLONESTYLE" = "none" ]
		then
			PARAMS="-ab --backup-dir=../0000"
		elif [ "$CLONESTYLE" = "hardlink" ]
		then
			PARAMS="-a --link-dest=../0000"
		else
			PARAMS="-a"
		fi
		[ ${#SOURCES[@]} -eq 1 ] && PARAMS="$PARAMS --delete"
		[ -f "$DEST/.daisync-exclude-from" ] && PARAMS="$PARAMS --exclude-from=$DEST/.daisync-exclude-from"
		echo "[$(date '+%F %H:%M:%S')]#rsync $PARAMS \"$SRC\" \"$DEST/.daisync\""
		set +e
		bash -c "rsync $PARAMS $SRC \"$DEST/.daisync\""
		RSYNC_RTN=$?
		set -e
		[ $RSYNC_RTN -eq 0 -o $RSYNC_RTN -eq 24 ] || helpme "ERR-012: rsync '$SRC' failed with code $RSYNC_RTN"
	done
	if [ "$UPDATEDB" = "YES" ]
	then
		echo "[$(date '+%F %H:%M:%S')]#create locate database"
		updatedb -l no -o "$DEST/.daisync/.daisync-locate.db" -U "$(realpath "$DEST/.daisync")"
		chmod 400 "$DEST/.daisync/.daisync-locate.db"
	fi
	df -Pm "$DEST" > "$DEST/.daisync/.daisync-df"
	((NUM--))
	for IDX in $(seq -f %04g $NUM -1 0)
	do
		if [ -d "$DEST/$IDX" ]
		then
			if [ "$IDX" = "$(printf "%04d" $NUM)" ]
			then
				rm -rf "$DEST/$IDX"
			else
				mv "$DEST/$IDX" "$DEST/$PREV"
			fi
		fi
		PREV=$IDX
	done
	mv "$DEST/.daisync" "$DEST/0000"
	wait
	
	if [ "$ARCHIVE" != "" ]
	then
		(( NOW=$(date +%s) ))
		if [ "$ARCHIVE" = "weekly" ]
		then
			(( OFFSET=$(date --date="@$NOW" +%w) ))
			(( START=$NOW - $OFFSET * 3600 * 24 ))
		elif [ "$ARCHIVE" = "monthly" ]
		then
			(( OFFSET=$(date --date="@$NOW" +%_d) ))
			(( OFFSET-- ))
			(( START=$NOW - $OFFSET * 3600 * 24 ))
		elif [ "$ARCHIVE" = "yearly" ]
		then
			(( OFFSET=$(date --date="@$NOW" +%_j) ))
			(( OFFSET-- ))
			(( START=$NOW - $OFFSET * 3600 * 24 ))
		fi
		HAS_ARCHIVE=NO
		for ((DT=$START; DT<=$NOW; DT+=3600 * 24))
		do
			DAY=$(date --date="@$DT" +%F)
			if ls "$DEST"/$DAY-??-??-?? &> /dev/null
			then
				HAS_ARCHIVE=YES
				break
			fi
		done
		if [ "$HAS_ARCHIVE" = "NO" ]
		then
			NOW=$(date --date="@$NOW" +%F-%H-%M-%S)
			echo "[$(date '+%F %H:%M:%S')]#creating $ARCHIVE archive"
			echo $NOW > "$DEST/0000/.daisync-archived"
			if [ "$CLONESTYLE" = "none" ]
			then
				cp -a "$DEST/0000/." "$DEST/$NOW"
			elif [ "$CLONESTYLE" = "hardlink" ]
			then
				cp -al "$DEST/0000/." "$DEST/$NOW"
			elif [ "$CLONESTYLE" = "reflink" ]
			then
				cp -a --reflink=always "$DEST/0000/." "$DEST/$NOW"
			else
				helpme "ERR-018"
			fi
		fi
	fi
	echo "[$(date '+%F %H:%M:%S')]#daisync end"
) 77> "$DEST/.daisync-lock" 2>&1 | tee "$DEST/.daisync-log.$$"
RTN=$?
if [ $RTN -eq 0 ]
then
	mv "$DEST/.daisync-log.$$" "$DEST/0000/.daisync-log"
	[ -f "$DEST/0000/.daisync-archived" ] && cp -a "$DEST/0000/.daisync-log" "$DEST/$(cat "$DEST/0000/.daisync-archived")/"
fi
exit $RTN
