#!/bin/bash
copyright () {
	echo -e "daisync-locate, file search tool for daisync.
Written by Manhong Dai, MBNI, University of Michigan.
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU GPL v3, and these copyright/history must stay
untouched.
There is NO WARRANTY, to the extent permitted by law.
See http://daisync.sf.net for detail:
Version 3.0.1
"
	exit 0
}
usage () {
	echo -e  "find files by name
Usage:: daisync-localte DIR [OPTIONS]... PATTERN...
  -h		display this help and exit
  -v		output version information and exit
DIR is either a folder that has all snapshots or a single snapshot
"
	exit 1
}
for CMD in locate
do
	if ! which $CMD &> /dev/null
	then
		echo "Command $CMD is needed for daisync-locate"
		exit 1
	fi
done

ARGS=("$@")
while getopts "hv" FLAG
do
	case "$FLAG" in
		h) 
			usage
			;;
		v)
			copyright
			;;
		*) 
			echo "Wrong option"
			usage
			;;
	esac
done


DIR="${ARGS[0]}"
if [ "$(ls $DIR/.daisync-locate.db $DIR/[0-9][0-9][0-9][0-9]/.daisync-locate.db 2> /dev/null | wc -l)" = "0" ]
then
	echo "$DIR is not a valid daisync backup location"
	exit 1
fi

shift
LOCATE_PARAMS=$*
ls $DIR/.daisync-locate.db $DIR/[0-9][0-9][0-9][0-9]/.daisync-locate.db 2> /dev/null | while read DB
do
	LOC=$(basename $(cd $(dirname $DB); pwd))
	locate -d $DB $LOCATE_PARAMS |sed -e "s/\/\.daisync\//\/$LOC\//"
done
